spring:
  profiles:
    active: dev   # 기본 활성 프로필

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/ledger?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    # driver-class-name: org.mariadb.jdbc.Driver   # (선택) 필요 시 명시

  jpa:
    hibernate:
      ddl-auto: validate        # 스키마는 Flyway, JPA는 검증만
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
        # default_batch_fetch_size: 50            # (선택) N+1 완화

  thymeleaf:
    cache: false

  flyway:
    enabled: true
    baseline-on-migrate: true   # ← 기존 스키마에 이력 테이블 없을 때 1회 베이스라인
    baseline-version: 1
    schemas:
      - ledger
    default-schema: ledger

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # 바인딩 파라미터 로그(개발용)

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # type-aliases-package: com.example.ledger.**   # (선택) MyBatis 병행 시 별칭 경로
