spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/accountbook?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate     # 스키마는 Flyway가 만들고 JPA는 검증만
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    open-in-view: false

  thymeleaf:
    cache: false

flyway:
  enabled: true
  locations: classpath:db/migration
  # 기존 DB에서 시작한다면(브라운필드) 아래 두 줄 활성화
  # baseline-on-migrate: true
  # baseline-version: 1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # 바인딩 파라미터 로그 (개발용만)

mybatis:
  mapper-locations: classpath:/mapper/*.xml
